### ISSUE TITLE
Images doesn't show up on the website

### ISSUE THREAD

**Issue by Sophie724** [Sophie724/using-svg-icons#1]
Hi Christian/ Anna,

For some reason the dinosaur svg image  doesn't show up on the internet. Can you take a look. Thank you.

[using-svg-icons-lesson.zip](https://github.com/Sophie724/using-svg-icons/files/7369554/using-svg-icons-lesson.zip)

@thatkidmadrid @anna-pokhilenko
.

**Comment by thatkidmadrid** [comment]
https://learn-the-web.algonquindesign.ca/courses/web-design-2/using-svg-icons/#step-6

Please make sure that you're previewing your page using the web server!

we've gone through this in class, so you can go through the class recording too, but essentially the browser is preventing your website from accessing files on your local machine (which is good for security purposes, but not so good for previewing). So, we use the included web server built into markbot to preview the file as intended

**Comment by thatkidmadrid** [comment]
also, please don't attach zips of your project to issues unless it's about something that isn't part of your repository! That's why we're using GitHub - so we are able to see your code

**Comment by Sophie724** [comment]
Thank you for your reply. :)
